
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/jbrodriguez/actor"
  version = "1.0.0"

[[constraint]]
  revision = "006dc6db226a30dddd9e8eab3cce1e44f651ed8a"
  name = "github.com/jbrodriguez/mlog"

[[constraint]]
  name = "github.com/jbrodriguez/pubsub"
  version = "1.0.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.3"

[[constraint]]
  revision = "257f7b9a7d87427c8d7f89469a5958d57f8abd7c"
  name = "github.com/mcuadros/go-version"

[[constraint]]
  name = "github.com/namsral/flag"
  version = "1.7.4-pre"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  revision = "a98ad7ee00ec53921f08832bc06ecf7fd600e6a1"
  name = "github.com/vaughan0/go-ini"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/teris-io/shortid"
  revision = "771a37caa5cf0c81f585d7b6df4dfc77e0615b5c"
